source 'https://rubygems.org'

gem 'nokogiri'
gem 'rack', '~> 2.0.1'
gem 'rspec'
gem 'github-pages'
gem 'rake'
gem 'rouge'
gem 'pygments.rb'
gem 'jekyll'
gem 'html-proofer'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
